# Generated by Django 2.1.10 on 2020-01-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_datetime', models.DateTimeField(auto_now_add=True)),
                ('winner_global_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('battle_counter', models.IntegerField(default=0)),
                ('badge_counter', models.IntegerField(default=0)),
                ('leagues_counter', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0)),
                ('loose_battles', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('trainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abp.Trainer')),
                ('role', models.CharField(choices=[('Gym Leader', 'Gym Leader'), ('Elite Four', 'Elite Four'), ('Champion', 'Champion')], max_length=20)),
                ('pokemon_type', models.CharField(max_length=100)),
                ('clauses', models.TextField(blank=True, null=True)),
            ],
            bases=('abp.trainer',),
        ),
    ]
