# Generated by Django 2.1.10 on 2020-02-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_datetime', models.DateTimeField(auto_now_add=True)),
                ('winner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Gym Leader', 'Gym Leader'), ('Elite Four', 'Elite Four'), ('Champion', 'Champion')], max_length=20)),
                ('pokemon_type', models.CharField(max_length=100)),
                ('clauses', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('lv', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('next_lv', models.IntegerField(default=5)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('battle_counter', models.IntegerField(default=0)),
                ('badge_counter', models.IntegerField(default=0)),
                ('leagues_counter', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0)),
                ('loose_percentage', models.FloatField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('fc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sd_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discord_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_champion', to='abp.Leader')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(to='abp.Badge')),
                ('battles', models.ManyToManyField(to='abp.Battle')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.League')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('lv', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('next_lv', models.IntegerField(default=5)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('battle_counter', models.IntegerField(default=0)),
                ('badge_counter', models.IntegerField(default=0)),
                ('leagues_counter', models.IntegerField(default=0)),
                ('win_percentage', models.FloatField(default=0)),
                ('loose_percentage', models.FloatField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('fc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sd_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discord_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
        ),
        migrations.AddField(
            model_name='league',
            name='competitors',
            field=models.ManyToManyField(related_name='league_competitors', to='abp.Trainer'),
        ),
        migrations.AddField(
            model_name='league',
            name='elite_four',
            field=models.ManyToManyField(related_name='league_elite_four', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='league',
            name='gym_leaders',
            field=models.ManyToManyField(related_name='league_gym_leaders', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='league',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_winner', to='abp.Trainer'),
        ),
        migrations.AddField(
            model_name='battle',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battling_leader', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battling_trainer', to='abp.Trainer'),
        ),
    ]
