# Generated by Django 2.1.10 on 2020-01-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_champion', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='league',
            name='competitors',
            field=models.ManyToManyField(null=True, related_name='league_competitors', to='abp.Trainer'),
        ),
        migrations.AddField(
            model_name='league',
            name='elite_four',
            field=models.ManyToManyField(null=True, related_name='league_elite_four', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='league',
            name='gym_leaders',
            field=models.ManyToManyField(null=True, related_name='league_gym_leaders', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='league',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_winner', to='abp.Trainer'),
        ),
    ]
