# Generated by Django 2.1.10 on 2020-01-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0002_auto_20200121_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='competitors',
            field=models.ManyToManyField(related_name='league_competitors', to='abp.Trainer'),
        ),
        migrations.AlterField(
            model_name='league',
            name='elite_four',
            field=models.ManyToManyField(related_name='league_elite_four', to='abp.Leader'),
        ),
        migrations.AlterField(
            model_name='league',
            name='gym_leaders',
            field=models.ManyToManyField(related_name='league_gym_leaders', to='abp.Leader'),
        ),
    ]
