# Generated by Django 2.1.10 on 2019-07-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0002_season_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='league',
            new_name='season_league',
        ),
        migrations.AddField(
            model_name='season',
            name='season_tournaments',
            field=models.ManyToManyField(to='abp.Tournament'),
        ),
    ]
