# Generated by Django 2.1.10 on 2019-07-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0003_auto_20190724_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_trainers',
            field=models.ManyToManyField(to='abp.Trainer'),
        ),
    ]
