# Generated by Django 2.1.10 on 2020-01-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0003_auto_20200121_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='loose_battles',
            new_name='loose_percentage',
        ),
    ]
