# Generated by Django 2.1.10 on 2020-01-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0004_auto_20200121_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='battles',
            field=models.ManyToManyField(to='abp.Battle'),
        ),
        migrations.AddField(
            model_name='score',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.League'),
        ),
        migrations.AddField(
            model_name='score',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
        ),
    ]
