# Generated by Django 2.1.10 on 2020-01-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0005_auto_20200122_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battling_leader', to='abp.Leader'),
        ),
        migrations.AddField(
            model_name='battle',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battling_trainer', to='abp.Trainer'),
        ),
    ]
