# Generated by Django 2.1.10 on 2019-07-25 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0005_auto_20190724_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguebattle',
            name='winner_nickname',
        ),
        migrations.AddField(
            model_name='leader',
            name='league_season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguebattle',
            name='battling_leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Leader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguebattle',
            name='battling_trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguebattle',
            name='winner_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguescore',
            name='league_reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentscore',
            name='tournament_reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerbattle',
            name='trainer_blue_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerbattle',
            name='trainer_red_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerbattle',
            name='winner_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
