# Generated by Django 2.1.10 on 2019-07-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0006_auto_20190725_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
