# Generated by Django 2.1.10 on 2020-01-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0007_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='badges',
            field=models.ManyToManyField(to='abp.Badge'),
        ),
    ]
