# Generated by Django 2.1.10 on 2020-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0008_score_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='total_loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
    ]
