# Generated by Django 2.1.10 on 2019-07-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0008_auto_20190727_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_key', models.CharField(max_length=50)),
                ('event_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('event_reference', 'score_key')},
        ),
    ]
