# Generated by Django 2.1.10 on 2019-07-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0009_auto_20190727_0351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='trainer_reference',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='score',
            name='event_reference',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
