# Generated by Django 2.1.10 on 2020-01-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0009_auto_20200123_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='total_loses',
            new_name='total_losses',
        ),
    ]
