# Generated by Django 2.1.10 on 2019-07-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0010_auto_20190728_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguescore',
            name='trainer_reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentscore',
            name='trainer_reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
            preserve_default=False,
        ),
    ]
