# Generated by Django 2.1.10 on 2020-01-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0010_auto_20200123_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='winner_global_id',
            new_name='winner_name',
        ),
    ]
