# Generated by Django 2.1.10 on 2019-07-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0011_auto_20190728_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentscore',
            name='tournament_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentscore',
            name='trainer_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.Trainer'),
        ),
    ]
