# Generated by Django 2.1.10 on 2020-01-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0011_auto_20200123_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
