# Generated by Django 2.1.10 on 2019-07-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0012_auto_20190728_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentscore',
            name='tournament_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abp.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguescore',
            unique_together={('league_reference', 'trainer_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentscore',
            unique_together={('tournament_reference', 'trainer_reference')},
        ),
    ]
