# Generated by Django 2.1.10 on 2020-01-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0012_auto_20200124_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='fc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='lv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='next_lv',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sd_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
