# Generated by Django 2.1.10 on 2019-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0013_auto_20190728_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='pokemon_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
