# Generated by Django 2.1.10 on 2020-01-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0013_auto_20200129_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
