# Generated by Django 2.1.10 on 2019-07-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0014_leader_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='league_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abp.League'),
        ),
    ]
