# Generated by Django 2.1.10 on 2020-02-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0015_auto_20200202_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='discord_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='fc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sd_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
