# Generated by Django 2.1.10 on 2019-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0015_auto_20190730_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscore',
            name='battles',
            field=models.ManyToManyField(to='abp.TrainerBattle'),
        ),
    ]
